config/routes.rb
Rails.application.routes.draw do
  resources :leads
  resources :firstnames
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'leads#index'
  get '/search' => 'leads#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
    def client
        Restforce.new(username: '<saleforce_userName>',
            password: '<salesforce_passaword>',
            security_token: '<salesforce_sercurityToken',
            client_id: '<salesforce_consumerKey',
            client_secret: '<salesforce_consumerSecret',
            api_version: "43.0")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all
  end

  def search
    @lead = Lead.where("id = #{params[:id]}")
    respond_to do |format|
      if @lead.empty?
          format.html { redirect_to leads_url, notice: 'We could not find a lead with that id'}
      else
        format.html { redirect_to @lead[0] }
      end
    end    
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)
    @salesforce = @lead.client.create('Lead', FirstName: @lead.firstname, LastName: @lead.lastname, Company: @lead.company, Email: @lead.email, Phone: @lead.phone)
    respond_to do |format|
      if @salesforce != false
        if @lead.save
          format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
          format.json { render :show, status: :created, location: @lead }
        else
          format.html { render :new }
          format.json { render json: @lead.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to :new, notice: 'Lead was could not be created please try again.' }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    @leadupdate = Lead.new
    @leadFind = @leadupdate.client.query("select Id from Lead where FirstName = '#{@lead.firstname}' and LastName = '#{@lead.lastname}' and Company = '#{@lead.company}'")
    @leadid = @leadFind.first.Id
    respond_to do |format|
      if @lead.update(lead_params)
        @SFleadUpdate = @leadupdate.client.update('Lead', Id: @leadid, FirstName: @lead.firstname, LastName: @lead.lastname, Email: @lead.email, Company: @lead.company)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @leadupdate = Lead.new
    @leadFind = @leadupdate.client.query("select Id from Lead where FirstName = '#{@lead.firstname}' and LastName = '#{@lead.lastname}' and Company = '#{@lead.company}'")
    @leadid = @leadFind.first.Id
    @SFleadupdate = @leadupdate.client.destroy('Lead', Id: @leadid)
    if @SFleadupdate != false
      @lead.destroy
      respond_to do |format|
        format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @lead, notice: 'Lead could not be destroyed' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:firstname, :lastname, :company, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firstnames_helper.rb
module FirstnamesHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestforceTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/leads/_form.html.erb
<%= form_with(model: lead, local: true) do |form| %>
  <% if lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>

  <form action='/search'>
    ID<input type="text" name='id'>
    <input type="submit" value="submit">
  </form></br>

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>You lead id:</strong>
  <%= @lead.id %> Please keep this as you will need it to lookup you lead status.
</p>


<p>
  <strong>Firstname:</strong>
  <%= @lead.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @lead.lastname %>
</p>

<p>
  <strong>Company:</strong>
  <%= @lead.company %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lead.phone %>
</p>
<%= link_to 'Destroy', @lead, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>